se.kth.iv1350.integration.DatabaseFailureException: DatabaseFailure. Caused by item: 666
	at se.kth.iv1350.integration.ItemRegistry.getItem(ItemRegistry.java:67)
	at se.kth.iv1350.controller.Controller.scanItem(Controller.java:63)
	at se.kth.iv1350.view.View.loopThroughInput(View.java:115)
	at se.kth.iv1350.view.View.sampleExcecution(View.java:95)
	at se.kth.iv1350.startup.Main.main(Main.java:35)
     This occurred at: 2018-05-20T17:58:36.197
